heat_template_version: 2013-05-23
description: A DB2 server node
parameters:
  flavor:
    type: string
    description: flavor used by the servers
  image:
    type: string
    description: Image used for servers
  key_name:
    type: string
    description: SSH key to connect to the servers
  chef_server_url:
    type: string
  nameserver:
    type: string     
resources:
  db2_config:
    type: OS::Heat::SoftwareConfig
    properties:
      inputs:
      - name: previous
        default: 'NONE'
      group: script
      config:
        str_replace:
          template: |
            #!/bin/bash
            export intfc=eth0
            export IP=`ifconfig $intfc | grep 'inet addr:' | cut -d: -f2 | awk '{ print $1}'`
            export HOSTNAME=`hostname`
            export DOMAIN=mgt
            export NAMESERVER=%nameserver%
             #save stdout and stderr to file descriptors 3 and 4, then redirect them to "config.log"
            exec 3>&1 4>&2 >db2_config.log 2>&1
            #Fix the etc/hosts file
            tee -a /etc/hosts <<EOF
            $IP $HOSTNAME $HOSTNAME.$DOMAIN
            EOF

            #Fix the DNS
            tee /etc/resolv.conf <<EOF
            search $DOMAIN
            nameserver $NAMESERVER
            EOF

            #Fix sshd to allow password access. The service will be restarted in the recipe.
            sed -i 's/^PasswordAuthentication.*/PasswordAuthentication yes/g' /etc/ssh/sshd_config
            service sshd restart

            #fix a lib required by DB2
            yum -y update numactl
            #install chef client
            curl -L https://www.getchef.com/chef/install.sh | bash

            #Set up the chef environment
            mkdir -p /etc/chef

            tee /etc/chef/client.rb <<EOF
            log_location     STDOUT
            chef_server_url  "https://%chef_server_url%:443"
            validation_client_name "chef-validator"
            #Using default node name (fqdn)
            EOF

            tee /etc/chef/validation.pem <<EOF
            -----BEGIN RSA PRIVATE KEY-----
            #Insert the key for your chef server 
            -----END RSA PRIVATE KEY-----
            EOF

            #Install DB2
            chef-client -o "recipe[db2]","recipe[db2::start]"
            #Allow sudo to run w/o access to tty
            sed -i 's/^Defaults    requiretty.*/#Defaults    requiretty/g' /etc/sudoers
            # Create database SAMPLE
            sudo -H -u db2inst1 bash -c ". ~/.bash_profile && db2sampl"
            #restore stdout and stderr
            exec 1>&3 2>&4
            #cat /tmp/db2.rsp
            ifconfig eth0 | grep 'inet addr:' | cut -d: -f2 | awk '{ print $1}'
          params:
            "%nameserver%" : { get_param: nameserver }
            "%chef_server_url%" : { get_param: chef_server_url}
  db2_deployment:
    type: OS::Heat::SoftwareDeployment
    properties:
      config:
        get_resource: db2_config
      server:
        get_resource: db2_server
  db2_server:
    type: OS::Nova::Server
    properties:
      flavor: {get_param: flavor}
      image: {get_param: image}
      key_name: {get_param: key_name}
      user_data_format: SOFTWARE_CONFIG

outputs:
    db2_server_name:
      value:
        get_attr: [ db2_server, networks, admin-net, 0 ]

